import type { IconType } from "react-icons";
import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNodedotjs,
  SiNextdotjs,
  SiSharp,
  SiCplusplus,
  SiC,
  SiRust,
  SiPython,
  SiUnity,
  SiUnrealengine,
  SiGodotengine,
  SiArduino,
  SiPytorch,
  SiTensorflow,
  SiPandas,
  SiGo,
  SiDart,
  SiFlutter,
  SiSwift,
  SiKotlin,
  SiRuby,
  SiPhp,
  SiLua,
  SiPerl,
  SiZig,
  SiOpenjdk,
  SiScala,
  SiHaskell,
  SiElixir,
  SiClojure,
  SiFsharp,
  SiErlang,
  SiR,
  SiJulia,
  SiFortran,
  SiVuedotjs,
  SiSvelte,
  SiAngular,
  SiDjango,
  SiRubyonrails,
  SiSpring,
  SiLaravel,
  SiScikitlearn,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiGithub,
  SiNumpy,
  SiFastapi,
  SiFlask,
  SiExpress,
  SiQt,
  SiDotnet,
  SiSymfony,
  SiPhoenixframework,
  SiKtor,
  SiAxios,
  SiJquery,
} from "react-icons/si";
import {
  LuCpu,
  LuBrain,
  LuSmartphone,
  LuBug,
  LuHammer,
  LuShield,
  LuBattery,
  LuCoffee,
  LuBriefcase,
  LuRocket,
  LuUsers,
  LuTrendingUp,
  LuArchive,
  LuShoppingCart,
  LuFolderKanban,
  LuFlame,
  LuBird,
  LuFileText,
  LuPlay,
  LuSquare,
  LuSave,
  LuPalette,
  LuCog,
  LuWrench,
  LuChartColumn,
  LuMicroscope,
  LuClipboardList,
  LuSparkles,
  LuMegaphone,
  LuLeaf,
  LuBanknote,
  LuBot,
  LuUserPlus,
  LuTrash2,
  LuBuilding2,
  LuBox,
  LuGitCommitHorizontal,
  LuPackage,
  LuKeyboard,
  LuSearch,
  LuTriangleAlert,
  LuBraces,
  LuSigma,
  LuDatabase,
  LuScroll,
  LuBinary,
  LuFileCode2,
  LuChevronRight,
  LuChevronDown,
  LuLightbulb,
  LuLibrary,
  LuBoxes,
  LuGraduationCap,
  LuMouse,
  LuShirt,
  LuScissors,
  LuCircleUser,
  LuMonitor,
  LuComputer,
  LuMicrochip,
  LuMemoryStick,
  LuHardDrive,
  LuCookingPot,
  LuUtensils,
  LuPizza,
  LuBeef,
  LuGlassWater,
  LuCupSoda,
  LuZap,
  LuWheat,
  LuFish,
  LuSalad,
  LuCroissant,
} from "react-icons/lu";

// Central icon registry. Data files reference these string ids (no JSX in data).
const ICONS: Record<string, IconType> = {
  // language-family group headers
  g_script: LuBraces,
  g_systems: LuCpu,
  g_enterprise: LuCoffee,
  g_native: LuSmartphone,
  g_func: LuSigma,
  g_data: LuDatabase,
  g_legacy: LuScroll,

  // languages (brand)
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  ruby: SiRuby,
  php: SiPhp,
  lua: SiLua,
  perl: SiPerl,
  c: SiC,
  cpp: SiCplusplus,
  rust: SiRust,
  go: SiGo,
  zig: SiZig,
  java: SiOpenjdk,
  kotlin: SiKotlin,
  scala: SiScala,
  csharp: SiSharp,
  swift: SiSwift,
  dart: SiDart,
  objc: LuFileCode2,
  haskell: SiHaskell,
  elixir: SiElixir,
  clojure: SiClojure,
  fsharp: SiFsharp,
  erlang: SiErlang,
  r: SiR,
  julia: SiJulia,
  sql: LuDatabase,
  cobol: LuScroll,
  fortran: SiFortran,
  asm: LuBinary,

  // frameworks (brand)
  react: SiReact,
  vue: SiVuedotjs,
  svelte: SiSvelte,
  angular: SiAngular,
  nextjs: SiNextdotjs,
  node: SiNodedotjs,
  django: SiDjango,
  rails: SiRubyonrails,
  spring: SiSpring,
  laravel: SiLaravel,
  flutter: SiFlutter,
  reactnative: SiReact,
  swiftui: SiSwift,
  compose: SiKotlin,
  unity: SiUnity,
  unreal: SiUnrealengine,
  godot: SiGodotengine,
  arduino: SiArduino,
  pytorch: SiPytorch,
  tensorflow: SiTensorflow,
  pandas: SiPandas,
  sklearn: SiScikitlearn,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  numpy: SiNumpy,
  fastapi: SiFastapi,
  flask: SiFlask,
  express: SiExpress,
  qt: SiQt,
  dotnet: SiDotnet,
  symfony: SiSymfony,
  phoenix: SiPhoenixframework,
  ktor: SiKtor,
  axios: SiAxios,
  jquery: SiJquery,

  // action categories
  concept: LuLightbulb,
  library: LuLibrary,
  framework: LuBoxes,
  oss: SiGithub,
  cert: LuGraduationCap,

  // craft skills
  cooking: LuCookingPot,
  pcbuild: LuComputer,

  // equipment slots / gear
  keyboard: LuKeyboard,
  mouse: LuMouse,
  shirt: LuShirt,
  hair: LuScissors,
  avatar: LuCircleUser,
  pc: LuMonitor,

  // PC parts
  cpu: LuCpu,
  gpu: LuMicrochip,
  ram: LuMemoryStick,
  ssd: LuHardDrive,

  // foods / drinks / ingredients
  water: LuGlassWater,
  cola: LuCupSoda,
  energy: LuZap,
  onigiri: LuUtensils,
  bento: LuUtensils,
  ramen: LuUtensils,
  pizza: LuPizza,
  sushi: LuFish,
  rice: LuWheat,
  noodles: LuUtensils,
  meat: LuBeef,
  fish_food: LuFish,
  veg: LuSalad,
  dough: LuCroissant,
  leave: LuLeaf,

  // combat stats
  debug: LuBug,
  impl: LuHammer,
  robust: LuShield,
  mental: LuBattery,

  // resources / concepts
  commit: LuGitCommitHorizontal,
  product: LuPackage,
  coffee: LuCoffee,
  editor: LuKeyboard,
  techdebt: LuTriangleAlert,
  kudos: LuSparkles,
  search: LuSearch,

  // tabs / ui
  career: LuTrendingUp,
  team: LuUsers,
  prestige: LuRocket,
  bank: LuArchive,
  shop: LuShoppingCart,
  projects: LuFolderKanban,
  company: LuBuilding2,
  stop: LuSquare,
  start: LuPlay,
  save: LuSave,
  fire: LuTrash2,
  hire: LuUserPlus,
  chevronRight: LuChevronRight,
  chevronDown: LuChevronDown,

  // job classes
  none: LuBriefcase,
  frontend: LuPalette,
  backend: LuCog,
  sre: LuWrench,
  data: LuChartColumn,
  qa: LuMicroscope,
  pm: LuClipboardList,
  fullstack: LuSparkles,
  security: LuShield,

  // prestige upgrades
  funding: LuBanknote,
  automation: LuBot,
  tech: LuBrain,
  brand: LuSparkles,
  wellness: LuLeaf,
  recruiting: LuMegaphone,
  delivery: LuFlame,

  // 案件 (monsters)
  bug_m: LuBug,
  newbie: LuBird,
  spec_change: LuFileText,
  review: LuSearch,
  incident: LuFlame,
  boss: LuBriefcase,
};

export interface IconProps {
  name?: string;
  size?: number;
  className?: string;
  color?: string;
  title?: string;
}

export function Icon({ name, size = 18, className, color, title }: IconProps) {
  const C = (name && ICONS[name]) || LuFileCode2;
  return (
    <C
      size={size}
      className={className}
      color={color}
      title={title}
      style={{ verticalAlign: "-0.15em", flexShrink: 0 }}
    />
  );
}
