import type { IconType } from "react-icons";
import { ITEM_ICONS } from "./itemIcons";
import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNodedotjs,
  SiNextdotjs,
  SiSharp,
  SiCplusplus,
  SiC,
  SiRust,
  SiPython,
  SiUnity,
  SiUnrealengine,
  SiGodotengine,
  SiArduino,
  SiPytorch,
  SiTensorflow,
  SiPandas,
  SiGo,
  SiDart,
  SiFlutter,
  SiSwift,
  SiKotlin,
  SiRuby,
  SiPhp,
  SiLua,
  SiPerl,
  SiZig,
  SiOpenjdk,
  SiScala,
  SiHaskell,
  SiElixir,
  SiClojure,
  SiFsharp,
  SiErlang,
  SiR,
  SiJulia,
  SiFortran,
  SiVuedotjs,
  SiSvelte,
  SiAngular,
  SiDjango,
  SiRubyonrails,
  SiSpring,
  SiLaravel,
  SiScikitlearn,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiLinux,
  SiGooglecloud,
  SiNginx,
  SiRaspberrypi,
  SiGithub,
  SiNumpy,
  SiFastapi,
  SiFlask,
  SiExpress,
  SiQt,
  SiDotnet,
  SiSymfony,
  SiPhoenixframework,
  SiKtor,
  SiAxios,
  SiJquery,
} from "react-icons/si";
import {
  LuCpu,
  LuBrain,
  LuSmartphone,
  LuBug,
  LuHammer,
  LuShield,
  LuBattery,
  LuCoffee,
  LuBriefcase,
  LuRocket,
  LuUsers,
  LuTrendingUp,
  LuArchive,
  LuShoppingCart,
  LuFolderKanban,
  LuFlame,
  LuBird,
  LuFileText,
  LuPlay,
  LuSquare,
  LuSave,
  LuPalette,
  LuCog,
  LuWrench,
  LuChartColumn,
  LuMicroscope,
  LuClipboardList,
  LuSparkles,
  LuLeaf,
  LuBanknote,
  LuBot,
  LuUserPlus,
  LuTrash2,
  LuBuilding2,
  LuBox,
  LuGitCommitHorizontal,
  LuPackage,
  LuKeyboard,
  LuSearch,
  LuTriangleAlert,
  LuBraces,
  LuSigma,
  LuDatabase,
  LuScroll,
  LuBinary,
  LuFileCode2,
  LuChevronRight,
  LuChevronDown,
  LuLightbulb,
  LuLibrary,
  LuBoxes,
  LuGraduationCap,
  LuMouse,
  LuShirt,
  LuScissors,
  LuCircleUser,
  LuMonitor,
  LuComputer,
  LuMicrochip,
  LuMemoryStick,
  LuHardDrive,
  LuCookingPot,
  LuUtensils,
  LuPizza,
  LuBeef,
  LuGlassWater,
  LuCupSoda,
  LuZap,
  LuWheat,
  LuSprout,
  LuShovel,
  LuFish,
  LuSalad,
  LuCroissant,
  LuRoute,
  LuBackpack,
  LuShoppingBag,
  LuBriefcaseBusiness,
  LuLayoutTemplate,
  LuBlocks,
  LuGlobe,
  LuServer,
  LuGamepad2,
  LuFactory,
  LuCloud,
  LuLandmark,
  LuHeartPulse,
  LuCircuitBoard,
  LuLayers,
  LuScale,
  LuBuilding,
} from "react-icons/lu";

// Central icon registry. Data files reference these string ids (no JSX in data).
const ICONS: Record<string, IconType> = {
  // language-family group headers
  g_script: LuBraces,
  g_systems: LuCpu,
  g_enterprise: LuCoffee,
  g_native: LuSmartphone,
  g_func: LuSigma,
  g_data: LuDatabase,
  g_legacy: LuScroll,

  // languages (brand)
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  ruby: SiRuby,
  php: SiPhp,
  lua: SiLua,
  perl: SiPerl,
  c: SiC,
  cpp: SiCplusplus,
  rust: SiRust,
  go: SiGo,
  zig: SiZig,
  java: SiOpenjdk,
  kotlin: SiKotlin,
  scala: SiScala,
  csharp: SiSharp,
  swift: SiSwift,
  dart: SiDart,
  objc: LuFileCode2,
  haskell: SiHaskell,
  elixir: SiElixir,
  clojure: SiClojure,
  fsharp: SiFsharp,
  erlang: SiErlang,
  r: SiR,
  julia: SiJulia,
  sql: LuDatabase,
  cobol: LuScroll,
  fortran: SiFortran,
  asm: LuBinary,

  // frameworks (brand)
  react: SiReact,
  vue: SiVuedotjs,
  svelte: SiSvelte,
  angular: SiAngular,
  nextjs: SiNextdotjs,
  node: SiNodedotjs,
  django: SiDjango,
  rails: SiRubyonrails,
  spring: SiSpring,
  laravel: SiLaravel,
  flutter: SiFlutter,
  reactnative: SiReact,
  swiftui: SiSwift,
  compose: SiKotlin,
  unity: SiUnity,
  unreal: SiUnrealengine,
  godot: SiGodotengine,
  arduino: SiArduino,
  pytorch: SiPytorch,
  tensorflow: SiTensorflow,
  pandas: SiPandas,
  sklearn: SiScikitlearn,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  numpy: SiNumpy,
  fastapi: SiFastapi,
  flask: SiFlask,
  express: SiExpress,
  qt: SiQt,
  dotnet: SiDotnet,
  symfony: SiSymfony,
  phoenix: SiPhoenixframework,
  ktor: SiKtor,
  axios: SiAxios,
  jquery: SiJquery,

  // action categories
  concept: LuLightbulb,
  library: LuLibrary,
  framework: LuBoxes,
  oss: SiGithub,
  cert: LuGraduationCap,

  // craft skills
  cooking: LuCookingPot,
  pcbuild: LuComputer,

  // equipment slots / gear
  keyboard: LuKeyboard,
  mouse: LuMouse,
  shirt: LuShirt,
  hair: LuScissors,
  avatar: LuCircleUser,
  pc: LuMonitor,

  // PC parts
  cpu: LuCpu,
  gpu: LuMicrochip,
  ram: LuMemoryStick,
  ssd: LuHardDrive,

  // foods / drinks / ingredients
  water: LuGlassWater,
  cola: LuCupSoda,
  energy: LuZap,
  onigiri: LuUtensils,
  bento: LuUtensils,
  ramen: LuUtensils,
  pizza: LuPizza,
  sushi: LuFish,
  rice: LuWheat,
  noodles: LuUtensils,
  meat: LuBeef,
  fish_food: LuFish,
  veg: LuSalad,
  dough: LuCroissant,
  leave: LuLeaf,
  farming: LuSprout,
  till: LuShovel,
  fertilizer: LuLeaf,
  // 作物アイコンは itemIcons.tsx の自作SVG（ITEM_ICONS が優先）。近似の流用はしない。

  // combat stats
  debug: LuBug,
  impl: LuHammer,
  robust: LuShield,
  mental: LuBattery,

  // resources / concepts
  commit: LuGitCommitHorizontal,
  product: LuPackage,
  coffee: LuCoffee,
  editor: LuKeyboard,
  techdebt: LuTriangleAlert,
  kudos: LuSparkles,
  search: LuSearch,

  // tabs / ui
  roadmap: LuRoute,
  career: LuTrendingUp,
  team: LuUsers,
  prestige: LuRocket,
  bank: LuArchive,
  shop: LuShoppingCart,
  projects: LuFolderKanban,
  company: LuBuilding2,
  stop: LuSquare,
  start: LuPlay,
  save: LuSave,
  fire: LuTrash2,
  hire: LuUserPlus,
  chevronRight: LuChevronRight,
  chevronDown: LuChevronDown,

  // job classes
  none: LuBriefcase,
  frontend: LuPalette,
  backend: LuCog,
  sre: LuWrench,
  data: LuChartColumn,
  qa: LuMicroscope,
  pm: LuClipboardList,
  fullstack: LuSparkles,
  security: LuShield,

  // prestige upgrades
  funding: LuBanknote,
  automation: LuBot,
  tech: LuBrain,
  brand: LuSparkles,
  wellness: LuLeaf,
  delivery: LuFlame,

  // カテゴリ / 領域 / インフラ / 業界ドメイン
  platform: LuLayers,
  infra: LuServer,
  domain: LuBriefcase,
  linux: SiLinux,
  aws: LuCloud,
  gcp: SiGooglecloud,
  azure: LuCloud,
  nginx: SiNginx,
  database: LuDatabase,
  web: LuGlobe,
  game: LuGamepad2,
  mobile: LuSmartphone,
  embedded: LuCpu,
  ai_data: LuBrain,
  ai: LuBrain,
  fintech: LuLandmark,
  ec: LuShoppingCart,
  healthcare: LuHeartPulse,
  legal: LuScale,
  public: LuBuilding,
  electronics: LuCircuitBoard,
  raspberrypi: SiRaspberrypi,
  robot: LuBot,

  // 装備: かばん
  bag: LuBackpack,
  tote: LuShoppingBag,
  bizbag: LuBriefcaseBusiness,

  // 案件 (monsters / freelance gigs)
  bug_m: LuBug,
  newbie: LuBird,
  spec_change: LuFileText,
  review: LuSearch,
  incident: LuFlame,
  boss: LuBriefcase,
  lp: LuLayoutTemplate,
  feature: LuBlocks,
  webapp: LuGlobe,
};

// 言語/フレームワークのブランド配色（公式色。暗すぎる色は暗背景で見えるよう明るめに調整）。
const BRAND_COLOR: Record<string, string> = {
  // languages
  javascript: "#F7DF1E", typescript: "#3178C6", python: "#4B8BBE", ruby: "#CC342D",
  php: "#8993BE", lua: "#5B6BC0", perl: "#5C7AB0", c: "#A8B9CC", cpp: "#00599C",
  rust: "#E07B53", go: "#00ADD8", zig: "#F7A41D", java: "#ED8B00", kotlin: "#A97BFF",
  scala: "#DC322F", csharp: "#68217A", swift: "#F05138", dart: "#0175C2", objc: "#5C9FE0",
  haskell: "#8C6FB0", elixir: "#9B6FC4", clojure: "#5881D8", fsharp: "#378BBA",
  erlang: "#C5163F", r: "#276DC3", julia: "#B07BC8", sql: "#5B9BD5", cobol: "#5B87BF",
  fortran: "#9B7BC4", asm: "#8A7CF0",
  // frameworks
  react: "#61DAFB", vue: "#4FC08D", svelte: "#FF3E00", angular: "#DD0031",
  nextjs: "#E8E8E8", node: "#6FBF4E", django: "#44B78B", rails: "#E33A3A",
  spring: "#6DB33F", laravel: "#FF2D20", flutter: "#48A8E0", reactnative: "#61DAFB",
  swiftui: "#F05138", compose: "#4285F4", unity: "#DEDEDE", unreal: "#CFCFCF",
  godot: "#5BA0CF", pytorch: "#EE4C2C", tensorflow: "#FF6F00", pandas: "#9B7BD4",
  sklearn: "#F7931E", docker: "#2496ED", kubernetes: "#4D7BE8", terraform: "#9468D4",
  express: "#BBBBBB", qt: "#41CD52", dotnet: "#7B5BD4", symfony: "#CCCCCC",
  phoenix: "#FD4F00", ktor: "#3B8CFA", numpy: "#4DABCF", fastapi: "#10AA98",
  flask: "#CCCCCC", axios: "#7A52E8", jquery: "#2780B8",
  // infra/cloud
  linux: "#F5C542", aws: "#FF9900", gcp: "#4285F4", nginx: "#2DA53F", raspberrypi: "#A22846",
};

export interface IconProps {
  name?: string;
  size?: number;
  className?: string;
  color?: string;
  title?: string;
}

export function Icon({ name, size = 18, className, color, title }: IconProps) {
  // 自作アイテムアイコンを優先（料理/パーツ/資源/ギア）。
  if (name && ITEM_ICONS[name]) {
    const el = ITEM_ICONS[name](size);
    return (
      <span
        className={className}
        title={title}
        style={{ display: "inline-flex", verticalAlign: "-0.15em" }}
      >
        {el}
      </span>
    );
  }
  const C = (name && ICONS[name]) || LuFileCode2;
  const brand = name ? BRAND_COLOR[name] : undefined;
  return (
    <C
      size={size}
      className={className}
      color={color ?? brand}
      title={title}
      style={{ verticalAlign: "-0.15em", flexShrink: 0 }}
    />
  );
}
